services:
  - type: web
    name: project-a1-genius
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn master_boot:app
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.10.0
        
